const TILE_WIDTH = 128;
const TILE_HEIGHT = 64;
const CHUNK_SIZE = 16;

export const TILES = {
  TILE_WIDTH,
  TILE_WIDTH_HALF: TILE_WIDTH / 2,
  TILE_HEIGHT,
  TILE_HEIGHT_HALF: TILE_HEIGHT / 2,
  CHUNK_SIZE,
  CHUNK_WIDTH: CHUNK_SIZE * TILE_WIDTH,
  CHUNK_HEIGHT: CHUNK_SIZE * TILE_HEIGHT,
} as const;
